#!/usr/bin/env python3.9

import sys
from Parser import *
from Partitioner import *

if __name__ == '__main__':
    parser = Parser()
    parser.parse(sys.argv[1:])
    heuristic, sort, limit, cores_number = parser.get_options()
    tasks = parser.get_tasks()
    partitioner = Partitioner(tasks, heuristic, sort, limit, cores_number)
    partitioner.run()

    if partitioner.is_partitioned():
        for core in partitioner.get_cores():
            print(core)
            core.schedule(limit)
    else:
        print("Cannot be partitioned")
